apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgd-app
  namespace: argocd
spec:
  destination:
    namespace: bgdk
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ch07/bgdui/bgdk
    repoURL: https://github.com/thetnaingtn/gitops-cookbook-sc
    targetRevision: grpc-course
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
