apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: production-updater
  namespace: argocd
spec:
  # Argo CD Applications live here
  namespace: argocd

  # Global defaults
  commonUpdateSettings:
    updateStrategy: "semver"

  # Global write-back config: use Git + a secret for credentials
  writeBackConfig:
    method: "git:secret:argocd/git-creds"

  applicationRefs:
    - namePattern: "bgd-app"

      # Per-app defaults
      commonUpdateSettings:
        pullSecret: github-packages-secret

      # Per-app Git config (no 'method' here, so it reuses the global one above)
      writeBackConfig:
        gitConfig:
          repository: "https://github.com/thetnaingtn/gitops-cookbook-sc.git"
          branch: "grpc-course"
          # Kustomize dir to update inside the repo
          writeBackTarget: "kustomization:ch07/bgdui/bgdk"

      images:
        - alias: "grpc-api"
          imageName: "ghcr.io/thetnaingtn/grpc-course/hello-server"
          commonUpdateSettings:
            allowTags: "regexp:^v[0-9]+\\.[0-9]+\\.[0-9]+-prod$"
